---
# Docker
install_docker: false

# Dotfiles
configure_dotfiles: true
dotfiles_repo: "https://github.com/staticdev/dotfiles-eg.git"
dotfiles_repo_version: main
dotfiles_files:
  - .tmux.conf
  - .vimrc
  - .zshrc

# IDEs
## Pycharm
install_pycharm: false
pycharm_flavor: community # you can also choose: professional or edu
## VSCode
install_vscode: false
vscode_extensions:
  - shan.code-settings-sync
## VSCodium (community-driven, freely-licensed binary distribution of Microsoft’s editor VSCode)
install_vscodium: true

# Python settings
python_developer: true
pyenv_python_versions:
  - 3.10.4
  - 3.9.13
  - 3.8.13
  - 3.7.13
pyenv_global:
  - 3.10.4
  - 3.9.13
  - 3.8.13
  - 3.7.13
pyenv_virtualenvs: []

# browser configs
## Firefox config (note: default profile for Debian is default-esr)
configure_firefox: false
firefox_profiles:
  default-esr:
    extensions:
      - ublock-origin
    preferences:
      network.cookie.cookieBehavior: 1
      privacy.donottrackheader.enabled: true
      signon.rememberSignons: false
## Brave install
install_brave: true

# keyboard config
configure_keyboard: true
keyboard_layout: us
keyboard_variant: intl
keyboard_c_cedilla: false

# SSH config
configure_ssh: true
ssh_key_type: ed25519 # you can also choose between: dsa, ecdsa and ed25519
# For RSA keys, the minimum size is 1024 bits and the default is 4096 bits. Generally, 2048 bits is considered sufficient.
# DSA keys must be exactly 1024 bits as specified by FIPS 186-2.
# For ECDSA keys, size determines the key length by selecting from one of three elliptic curve sizes: 256, 384 or 521 bits.
# Attempting to use bit lengths other than these three values for ECDSA keys will cause this module to fail.
# Ed25519 keys have a fixed length and the size will be ignored.
ssh_key_size:
ssh_key_passphrase: super_secret_password

# sudoers config
configure_sudoers: false
sudoers_custom_config: ""
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

# terminal config
## Guake config
configure_terminal: true
guake_keybinding: "F12"

## ZSH config
install_zsh: true
zsh_default_shell: true

# Git config
setup_git: true
git_init_default_branch: main
git_pull_rebase: false
## create workspace folders with specific configs
git_create_workspaces: true
git_workspaces:
  - folder_name: workspace
    email: name@mail.com
    username: gitusername
#  - folder_name: workspace2
#    email: name2@mail.com
#    username: gitusername2
## used only if git_create_workspaces is false
git_email: name@mail.com
git_username: gitusername

# install packages
install_packages: true
# remove libreoffice in favor to onlyoffice
# onlyoffice is installed on snap_packages
remove_libreoffice: true
installed_packages:
  - apache2-utils
  - cmake
  - containerd # container runtime
  - dconf-editor # visual gnome configs
  - gir1.2-clutter-1.0 # dep gnome extension system monitor
  - gir1.2-clutter-gst-3.0 # dep gnome extension system monitor
  - gir1.2-gtkclutter-1.0 # dep gnome extension system monitor
  - git
  - guake
  - htop
  - locales-all
  - nmap
  - node
  - openssl
  - poedit
  - thefuck
  - tmux
  - vagrant
  - vim
  - xclip
  - wget

# install packages from other package managers.
install_extra_packages: true
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
snap_packages:
  - name: onlyoffice-desktopeditors
  - name: postman
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: black
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Gnome config
gnome_setup: true
gnome_favorite_apps:
  [
    "firefox-esr.desktop",
    "brave-browser.desktop",
    "org.gnome.Nautilus.desktop",
    "codium.desktop",
  ]

# enable entire screen sharing
enable_screen_sharing: true

# extra installs
## cryptomator
install_cryptomator: false
cryptomator_version: 1.6.10

install_keypass_xc: false
install_obs: false
install_openrgb: false
install_signal: false

# glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
