---
# Dotfiles (requires git enabled on nixpkgs)
configure_dotfiles: true
dotfiles_repo: "https://github.com/staticdev/dotfiles-eg.git"
dotfiles_repo_version: main
dotfiles_files:
  - .tmux.conf
  - .zshrc

# SSH config
configure_ssh: true
ssh_key_type: ed25519  # you can also choose between: dsa, ecdsa and ed25519
# For RSA keys, the minimum size is 1024 bits and the default is 4096 bits. Generally, 2048 bits is considered sufficient.
# DSA keys must be exactly 1024 bits as specified by FIPS 186-2.
# For ECDSA keys, size determines the key length by selecting from one of three elliptic curve sizes: 256, 384 or 521 bits.
# Attempting to use bit lengths other than these three values for ECDSA keys will cause this module to fail.
# Ed25519 keys have a fixed length and the size will be ignored.
ssh_key_size:
ssh_key_passphrase: super_secret_password

# Sudoers config
configure_sudoers: false
sudoers_custom_config: ""
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

# Terminal config
## Guake config
configure_terminal: true
guake_keybinding: "F12"

# Git config
setup_git: true
git_init_default_branch: main
git_pull_rebase: false
## create workspace folders with specific configs
git_create_workspaces: true
git_workspaces:
  - folder_name: workspace
    email: name@mail.com
    username: gitusername
#  - folder_name: workspace2
#    email: name2@mail.com
#    username: gitusername2
## used only if git_create_workspaces is false
git_email: name@mail.com
git_username: gitusername

# Gnome config
gnome_setup: false
gnome_favorite_apps:
  [
    "brave-browser.desktop",
    "org.gnome.Nautilus.desktop",
    "codium.desktop",
  ]

# enable entire screen sharing
enable_screen_sharing: false

# glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
