---
# Install packages
install_packages: true
installed_packages:
  - apache2-utils
  - cmake
  - dconf-editor  # visual gnome configs
  - gir1.2-clutter-1.0  # dep gnome extension system monitor
  - gir1.2-clutter-gst-3.0  # dep gnome extension system monitor
  - gir1.2-gtkclutter-1.0  # dep gnome extension system monitor
  - git
  - locales-all
  - openssl
  - podman  # see https://github.com/NixOS/nixpkgs/issues/138423
  - poedit

nix_packages:
  - name: kubectl
    check_cmd: kubectl version --client
  - name: helm
    check_cmd: helm --version
  - name: k9s
    check_cmd: k9s version
  - name: htop
    check_cmd: htop --version
  - name: nmap
    check_cmd: nmap --version
  - name: thefuck
    check_cmd: thefuck --version
  - name: tmux
    check_cmd: tmux -V
  - name: vagrant
    check_cmd: vagrant --version
  - name: vim
    check_cmd: vim --version
  - name: wget
    check_cmd: wget --version
  - name: xclip
    check_cmd: xclip -version

# Install packages from other package managers
install_extra_packages: true
# Note: You are responsible for adding the required package managers
# installation, eg. through nix
snap_packages: []
# - name: postman
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A

# Dotfiles (requires git on installed_packages or extra_packages)
configure_dotfiles: true
dotfiles_repo: "https://github.com/staticdev/dotfiles-eg.git"
dotfiles_repo_version: main
dotfiles_files:
  - .tmux.conf
  - .vimrc
  - .zshrc

# Keyboard config
configure_keyboard: false
keyboard_layout: us
keyboard_variant: intl
keyboard_c_cedilla: false

# SSH config
configure_ssh: true
ssh_key_type: ed25519  # you can also choose between: dsa, ecdsa and ed25519
# For RSA keys, the minimum size is 1024 bits and the default is 4096 bits. Generally, 2048 bits is considered sufficient.
# DSA keys must be exactly 1024 bits as specified by FIPS 186-2.
# For ECDSA keys, size determines the key length by selecting from one of three elliptic curve sizes: 256, 384 or 521 bits.
# Attempting to use bit lengths other than these three values for ECDSA keys will cause this module to fail.
# Ed25519 keys have a fixed length and the size will be ignored.
ssh_key_size:
ssh_key_passphrase: super_secret_password

# Sudoers config
configure_sudoers: false
sudoers_custom_config: ""
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

# Terminal config
## Guake config
configure_terminal: true
guake_keybinding: "F12"

# Git config
setup_git: true
git_init_default_branch: main
git_pull_rebase: false
## create workspace folders with specific configs
git_create_workspaces: true
git_workspaces:
  - folder_name: workspace
    email: name@mail.com
    username: gitusername
#  - folder_name: workspace2
#    email: name2@mail.com
#    username: gitusername2
## used only if git_create_workspaces is false
git_email: name@mail.com
git_username: gitusername

# Gnome config
gnome_setup: false
gnome_favorite_apps:
  [
    "firefox.desktop",
    "brave-browser.desktop",
    "org.gnome.Nautilus.desktop",
    "codium.desktop",
  ]

# enable entire screen sharing
enable_screen_sharing: false

# extra installs
## cryptomator
install_cryptomator: false
cryptomator_version: 1.11.1

install_keypass_xc: false
install_rclone: false

## openrgb
install_openrgb: false
# get from https://gitlab.com/CalcProgrammer1/OpenRGB/-/tags
openrgb_git_release: release_0.9
openrgb_deb_version: 0.9.0
openrgb_deb_architecture: amd64

# glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
