---
- name: Define hosts
  hosts: all

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: SSH and become checks
      ansible.builtin.include_tasks: tasks/site.yml

    - name: Load config
      ansible.builtin.include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"

  handlers:
    - name: Restart gnome
      ansible.builtin.command: killall -SIGQUIT gnome-shell
      changed_when: true

  tasks:
    - name: Create SSH key
      ansible.builtin.include_tasks: tasks/ssh.yml
      when: configure_ssh

    - name: Configure sudoers
      ansible.builtin.include_tasks: tasks/sudoers.yml
      when: configure_sudoers

    - name: Enable entire screen sharing
      ansible.builtin.lineinfile:
        dest: /etc/gdm3/daemon.conf
        regexp: '^#\s*WaylandEnable=false.*$'
        line: "WaylandEnable=false"
      become: true
      when: enable_screen_sharing

    - name: Run configured post-provision ansible task files.
      ansible.builtin.include_tasks: "{{ outer_item }}"
      loop_control:
        loop_var: outer_item
      with_fileglob: "{{ post_provision_tasks | default(omit) }}"
