---
roles:
  - name: ableton.nix
    version: 0.0.7
  - name: gantsign.golang
    version: 3.1.5
  - name: geerlingguy.docker
    version: 6.1.0
  - name: geerlingguy.dotfiles
    version: 1.2.1
  - name: geerlingguy.nodejs
    version: 6.1.1
  - name: green_leader.codium
    version: 1.0.4
  - name: robertdebock.obsproject
    version: 2.0.7
  - name: staticdev.brave
    version: 1.3.1
  - name: staticdev.firefox
    version: 2.0.5
  - name: staticdev.python_developer
    version: 2.5.1
  - name: staticdev.signal
    version: 1.6.1
  - name: stefangweichinger.ansible_rclone
    version: 0.1.2

collections:
  - name: community.general
    version: 7.1.0
  - name: community.crypto
    version: 2.14.0
