---
roles:
  - name: ableton.nix
    version: 0.0.8
  - name: gantsign.golang
    version: 3.2.4
  - name: geerlingguy.docker
    version: 6.1.0
  - name: geerlingguy.dotfiles
    version: 1.2.1
  - name: geerlingguy.nodejs
    version: 6.1.1
  - name: green_leader.codium
    version: 1.0.4
  - name: robertdebock.obsproject
    version: 2.0.7
  - name: staticdev.brave
    version: 1.3.2
  - name: staticdev.firefox
    version: 2.0.6
  - name: staticdev.pyenv
    version: 2.10.2
  - name: staticdev.python_developer
    version: 3.0.0
  - name: staticdev.signal
    version: 1.6.2
  - name: stefangweichinger.ansible_rclone
    version: 0.1.2

collections:
  - name: community.general
    version: 8.0.2
  - name: community.crypto
    version: 2.16.0
