---
roles:
  - name: geerlingguy.dotfiles
    version: 1.2.1
  - name: stefangweichinger.ansible_rclone
    version: 0.1.3

collections:
  - name: community.general
    version: 9.5.2
  - name: community.crypto
    version: 2.22.3
