---
roles:
  - name: gantsign.golang
    version: 3.1.3
  - name: geerlingguy.docker
    version: 6.1.0
  - name: geerlingguy.dotfiles
    version: 1.2.1
  - name: geerlingguy.nodejs
    version: 6.1.1
  - name: green_leader.codium
    version: 1.0.4
  - name: robertdebock.obsproject
    version: 2.0.6
  - name: staticdev.brave
    version: 1.2.1
  - name: staticdev.firefox
    version: 1.3.0
  - name: staticdev.python_developer
    version: 2.3.1
  - name: staticdev.signal
    version: 1.5.0
  - name: stefangweichinger.ansible_rclone
    version: 0.1.2

collections:
  - name: community.general
    version: 7.0.1
  - name: community.crypto
    version: 2.14.0
