---
roles:
  - name: gantsign.golang
    version: 3.0.4
  - name: gantsign.visual-studio-code
    version: 6.10.0
  - name: geerlingguy.docker
    version: 6.0.1
  - name: geerlingguy.dotfiles
    version: 1.2.1
  - name: green_leader.codium
    version: 1.0.4
  - name: robertdebock.obsproject
    version: 2.0.5
  - name: staticdev.brave
    version: 1.0.1
  - name: staticdev.firefox
    version: 1.2.0
  - name: staticdev.python_developer
    version: 2.1.0
  - name: staticdev.signal
    version: 1.3.4
  - name: stefangweichinger.ansible_rclone

collections:
  - name: community.general
    version: 6.0.0
  - name: community.crypto
    version: 2.8.0
