---
roles:
  - name: gantsign.golang
    version: 3.2.5
  - name: geerlingguy.dotfiles
    version: 1.2.1
  - name: geerlingguy.nodejs
    version: 6.1.1
  - name: staticdev.pyenv
    version: 2.11.0
  - name: staticdev.python_developer
    version: 3.1.0
  - name: stefangweichinger.ansible_rclone
    version: 0.1.3

collections:
  - name: community.general
    version: 9.5.2
  - name: community.crypto
    version: 2.22.3
