---
roles:
  - name: staticdev.firefox
    version: 1.1.0
  - name: staticdev.brave
    version: 1.0.0
  - name: geerlingguy.docker
    version: 4.1.3
  - name: robertdebock.obsproject
    version: 2.0.4
  - name: staticdev.python_developer
    version: 2.0.0
  - name: staticdev.signal
    version: 1.3.2
  - name: green_leader.codium
    version: 1.0.4
    when: install_vscodium
  - name: gantsign.visual-studio-code
    version: 6.8.0
    when: install_vscode

collections:
  - name: community.general
    version: 4.6.1
  - name: community.crypto
    version: 2.2.3
