---
- name: Install python-psutil package
  ansible.builtin.apt:
    name: python3-psutil
  become: true

- name: Install System Monitor extension
  ansible.builtin.package:
    name: gnome-shell-extension-system-monitor
    state: present
  become: true

- name: Enable System Monitor extension
  community.general.dconf:
    key: /org/gnome/shell/enabled-extensions
    value: ["system-monitor@paradoxxx.zero.gmail.com"]
  notify:
    - Restart gnome

- name: Setup night-light
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
  with_items:
    # values from gsettings list-recursively org.gnome.settings-daemon.plugins.color
    - key: "/org/gnome/settings-daemon/plugins/color/night-light-temperature"
      value: uint32 2700
    - key: "/org/gnome/settings-daemon/plugins/color/night-light-enabled"
      value: "true"
    - key: "/org/gnome/settings-daemon/plugins/color/night-light-schedule-automatic"
      value: "false"
    - key: "/org/gnome/settings-daemon/plugins/color/night-light-schedule-to"
      value: 6.0
    - key: "/org/gnome/settings-daemon/plugins/color/night-light-last-coordinates"
      value: (91.0, 181.0)
    - key: "/org/gnome/settings-daemon/plugins/color/active"
      value: "true"
    - key: "/org/gnome/settings-daemon/plugins/color/priority"
      value: 0
    - key: "/org/gnome/settings-daemon/plugins/color/night-light-schedule-from"
      value: 16.0

- name: Setup favorite-apps
  community.general.dconf:
    key: /org/gnome/shell/favorite-apps
    value: "{{ gnome_favorite_apps }}"

- name: Disable activities overview hot corner
  community.general.dconf:
    key: /org/gnome/desktop/interface/enable-hot-corners
    value: "false"

- name: Disable lock-screen notifications
  community.general.dconf:
    key: /org/gnome/desktop/notifications/show-in-lock-screen
    value: "false"
