---
- name: "Add home-manager channel"
  ansible.builtin.command: "nix-channel --add https://github.com/nix-community/home-manager/archive/master.tar.gz home-manager"
  environment:
    PATH: "{{ ansible_env.HOME + '/.nix-profile/bin:$PATH' }}"
  changed_when: false

- name: "Get channel updates"
  ansible.builtin.command: "nix-channel --update"
  environment:
    PATH: "{{ ansible_env.HOME + '/.nix-profile/bin:$PATH' }}"
  changed_when: false

- name: "Add Home Manager"
  ansible.builtin.command: "nix-shell '<home-manager>' -A install"
  environment:
    PATH: "{{ ansible_env.HOME + '/.nix-profile/bin:$PATH' }}"
    # workaround of https://github.com/nix-community/home-manager/issues/3944
    USER: $(id -un)
  changed_when: true
