---
- name: Check installation of Home Manager
  ansible.builtin.command: home-manager --version
  environment:
    PATH: "{{ ansible_env.HOME + '/.nix-profile/bin:$PATH' }}"
  register: home_manager_cmd
  changed_when: false
  ignore_errors: true

- name: Add Home Manager channel
  when: home_manager_cmd is failed
  ansible.builtin.command: "nix-channel --add https://github.com/nix-community/home-manager/archive/master.tar.gz home-manager"
  environment:
    PATH: "{{ ansible_env.HOME + '/.nix-profile/bin:$PATH' }}"
  changed_when: false

- name: Get channel updates
  when: home_manager_cmd is failed
  ansible.builtin.command: "nix-channel --update"
  environment:
    PATH: "{{ ansible_env.HOME + '/.nix-profile/bin:$PATH' }}"
  changed_when: false

- name: Add Home Manager
  when: home_manager_cmd is failed
  ansible.builtin.command: "nix-shell '<home-manager>' -A install"
  environment:
    PATH: "{{ ansible_env.HOME + '/.nix-profile/bin:$PATH' }}"
    # workaround of https://github.com/nix-community/home-manager/issues/3944
    USER: "{{ lookup('ansible.builtin.pipe', 'id -un') }}"
  changed_when: true
