---
- name: Check installation of Keepass XC
  ansible.builtin.command: keepassxc --version
  register: keepass_xc_cmd
  changed_when: false
  ignore_errors: true
- name: Install Keepass XC
  when: keepass_xc_cmd is failed
  ansible.builtin.command:
    cmd: nix-env -iA nixpkgs.keepassxc
  become: true
  become_user: "{{ workspace_user }}"
  environment:
    PATH: "{{ workspace_user_details.home + '/.nix-profile/bin:$PATH' }}"
  changed_when: true
