---
- name: Python - basic install
  become: true
  ansible.builtin.package:
    name: python3
    state: present

- name: Only run update cache if the last one is more than 3600 seconds ago
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  become: true

- name: Ensure packages are installed
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  become: true
  with_items:
    - "{{ installed_packages }}"

- name: Install Nix package manager
  ansible.builtin.import_role:
    name: ableton.nix
  vars:
    nix_flakes: true

- name: Add Nix to bash PATH
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: 'export PATH="{{ ansible_env.HOME }}/.nix-profile/bin:$PATH"'
    insertafter: EOF
    state: present
