---
- name: Python - basic install
  become: true
  ansible.builtin.package:
    name: python3
    state: present

- name: Only run update cache if the last one is more than 3600 seconds ago
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  become: true

- name: Ensure packages are installed
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  become: true
  with_items:
    - "{{ installed_packages }}"

- name: Install Nix package manager
  ansible.builtin.import_role:
    name: ableton.nix
  vars:
    nix_user: "{{ workspace_user }}"

- name: "Check installation of nix package {{ item.name }}"
  ansible.builtin.command: "{{ item.check_cmd }}"
  register: package_check_cmd
  changed_when: false
  ignore_errors: true
  loop: "{{ nix_packages }}"
  loop_control:
    index_var: package_index

- name: "Install nix package {{ item.name }}"
  ansible.builtin.command: "nix-env -iA nixpkgs.{{ item.name }}"
  become: true
  become_user: "{{ workspace_user }}"
  environment:
    PATH: "{{ workspace_user_details.home + '/.nix-profile/bin:$PATH' }}"
  when: package_check_cmd.results[package_index].failed
  changed_when: true
  loop: "{{ nix_packages }}"
  loop_control:
    index_var: package_index
