---
- name: Python - basic install
  become: true
  ansible.builtin.package:
    name: python
    state: present

- name: Only run update cache if the last one is more than 3600 seconds ago
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  become: true

- name: Ensure packages are installed
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  become: true
  with_items:
    - "{{ installed_packages }}"

- name: Remove LibreOffice
  ansible.builtin.package:
    name: "libreoffice*"
    state: absent
  become: true
  when: remove_libreoffice
