---
- name: Pycharm professional
  when: pycharm_flavor == 'professional'
  block:
    - name: Check installation of Pycharm professional
      ansible.builtin.command: pycharm-professional --version
      register: pycharm_version_cmd
      changed_when: false
      ignore_errors: true
    - name: Install Pycharm professional
      when: pycharm_version_cmd is failed
      ansible.builtin.command:
        cmd: nix-env -iA nixpkgs.jetbrains.pycharm-professional --impure
      become: true
      become_user: "{{ workspace_user }}"
      environment:
        NIXPKGS_ALLOW_UNFREE: "1"
        PATH: "{{ workspace_user_details.home + '/.nix-profile/bin:$PATH' }}"
      changed_when: true

- name: Pycharm community
  when: pycharm_flavor == 'community'
  block:
    - name: Check installation of Pycharm community
      ansible.builtin.command: pycharm-community --version
      register: pycharm_version_cmd
      changed_when: false
      ignore_errors: true
    - name: Install Pycharm community
      when: pycharm_version_cmd is failed
      ansible.builtin.command:
        cmd: nix-env -iA nixpkgs.jetbrains.pycharm-community
      become: true
      become_user: "{{ workspace_user }}"
      environment:
        PATH: "{{ workspace_user_details.home + '/.nix-profile/bin:$PATH' }}"
      changed_when: true
