---
- name: Ensure snapd is installed
  ansible.builtin.package:
    name: snapd
    state: present
  become: true

- name: Install pycharm
  community.general.snap:
    name: "pycharm-{{ pycharm_flavor }}"
    classic: true
  become: true
