---
- name: Check ssh password first
  ansible.builtin.command: echo "ssh password correct"
  changed_when: false

- name: Check sudo password first
  ansible.builtin.command: echo "sudo password correct"
  become: true
  changed_when: false
