---
- name: Add guake terminal to autostart.
  copy:
    src: /usr/share/applications/guake.desktop
    dest: /etc/xdg/autostart/
    mode: 0644
  become: true
  when: "'guake' in installed_packages"

- name: Add keybinding for Guake in Wayland
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
  with_items:
    # values from gsettings list-recursively /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings
    - key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings"
      value:
        [
          "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/guake/",
        ]
    - key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/guake/binding"
      value: "'{{ guake_keybinding }}'"
    - key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/guake/command"
      value: "'/usr/bin/guake-toggle'"
    - key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/guake/name"
      value: "'Guake'"
  when: "'guake' in installed_packages"
