---
- name: Install vscode
  ansible.builtin.include_role:
    name: gantsign.visual-studio-code
  vars:
    users:
      - username: "{{ lookup('env', 'USER') }}"
        visual_studio_code_extensions: "{{ vscode_extensions }}"
