---
- name: Install zsh package
  ansible.builtin.apt:
    name: zsh
  become: true

- name: Set zsh as default
  ansible.builtin.user:
    name: "{{ workspace_user }}"
    shell: /usr/bin/zsh
  become: true
  when: zsh_default_shell
