---
- name: Converge
  hosts: all
  become: true

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Install required packages
      ansible.builtin.apt:
        name:
          - firefox-esr
          - gpg
          - python3-bcrypt
          - python3-requests

- name: Import playbook
  import_playbook: ../../main.yml
