---
dependency:
  name: galaxy
driver:
  name: podman
lint: |
  set -e
  yamllint .
platforms:
  - name: instance
    image: "docker.io/staticdev/docker-${MOLECULE_DISTRO:-debian12}-ansible:latest"
    cgroupns_mode: host
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    pre_build_image: true
provisioner:
  name: ansible
  config_options:
    defaults:
      remote_user: molecule
verifier:
  name: ansible
